### ISSUE TITLE
高清接口F不行了

### ISSUE THREAD

**Issue by HENRIETTALU** [here200/Watch-Video-By-Interface#1]
如题

**Comment by codeLearner000** [comment]
我测试了一下，高清接口F还是可以用的。

**Comment by here200** [comment]
我测试了一下，高清接口F还是可以用的。

**Comment by here200** [comment]
![image](https://user-images.githubusercontent.com/41093691/180597245-41600d9c-9937-4451-91ae-ade0624f263b.png)

**Comment by HENRIETTALU** [comment]
我这边不行，显示player.maqq.cn意外终止了连接

**Comment by here200** [comment]
这个是你网络的问题。换个浏览器试试，或者过几天再试试。
